### ISSUE TITLE
Finetune Vicuna with qlora 

### ISSUE THREAD

**Issue by chinwh2019** [Lightning-AI/lit-gpt#459]
Hello, 

I tried to finetune vicuna-7b-v1.5 with qlora with RTX3090. 

i use the script below:
`python finetune/lora.py  --data_dir data/mydata/   --precision "bf16-true" --quantize "bnb.nf4-dq" --checkpoint_dir /AIDEV/llm/vicuna-7b-v1.5 --out_dir /AIDEV/llm/out/lora/vicuna`

but I got the error as below:
OutOfMemoryError: CUDA out of memory. Tried to allocate 86.00 MiB. GPU 0 has a total capacty of 23.69 GiB of which 83.94 MiB is free. Including 
non-PyTorch memory, this process has 23.57 GiB memory in use. Of the allocated memory 22.22 GiB is allocated by PyTorch, and 1.04 GiB is reserved by 
PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory
Management and PYTORCH_CUDA_ALLOC_CONF

Does it mean that Vicuna is not supported by lit-gpt?

Looking forward to your reply.

**Comment by rasbt** [comment]
If you haven't tried it, yet, could you try lower the microbatch size from 

```python
micro_batch_size = 4
```

to 

```python
micro_batch_size = 4
```

**Comment by chinwh2019** [comment]
@rasbt Thank you so much for your response! It works perfectly now! I will close this issue. Cheers!

**Comment by carmocca** [comment]
I'd say that the issue is that you can configure the model config, but not the micro batch size, and they usually go in hand. Maybe we should land #286

**Comment by rasbt** [comment]
Yes, perhaps. I think changing the microbatch size is such a common thing that a CLI argument would be helpful here.
